name: Node.js CI

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        CI: false
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
            NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Run tests
        run: yarn run test -- --coverage --no-watch --watch=false --watchAll=false --no-watchman --detectOpenHandles --forceExit --passWithNoTests
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
            NPM_TOKEN: ${{secrets.NPM_TOKEN}}